name: angel_jinja
description: Angel support for the Jinja2 templating engine, ported from Python to Dart.
version: 1.0.0-rc.1
homepage: https://github.com/angel-dart/jinja
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: '>=2.7.1 <3.0.0'
dependencies:
  angel_framework: ^2.1.0
  jinja: ^0.2.2
dev_dependencies:
  angel_test: ^2.0.1
  path: ^1.6.4
  pedantic: ^1.9.0
  test: ^1.11.1
